# Generated by Django 5.2.17 on 2026-09-13 19:14

import django.db.models.deletion
import django.db.models.functions.text
import django.db.models.lookups
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('study', '0002_content'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Note',
            fields=[
                ('id', models.UUIDField(editable=False, primary_key=True, serialize=False)),
                ('kind', models.CharField(choices=[('sticky', 'Sticky'), ('text', 'Text')], max_length=6)),
                ('text', models.TextField(max_length=20000)),
                ('x', models.FloatField(blank=True, null=True)),
                ('y', models.FloatField(blank=True, null=True)),
                ('version', models.PositiveIntegerField(default=1)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('article', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notes', to='study.article')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('created_at', 'id'),
                'indexes': [models.Index(fields=['user', 'article', 'created_at', 'id'], name='note_owner_article_order')],
                'constraints': [models.CheckConstraint(condition=models.Q(('kind__in', ('sticky', 'text'))), name='note_kind_valid'), models.CheckConstraint(condition=models.Q(('version__gte', 1)), name='note_version_positive'), models.CheckConstraint(condition=django.db.models.lookups.LessThanOrEqual(django.db.models.functions.text.Length('text'), 20000), name='note_text_length'), models.CheckConstraint(condition=models.Q(models.Q(('x__isnull', True), ('y__isnull', True)), models.Q(('x__gte', 0), ('x__isnull', False), ('x__lte', 1000000), ('y__gte', 0), ('y__isnull', False), ('y__lte', 1000000)), _connector='OR'), name='note_coordinates_pair_and_bounds')],
            },
        ),
    ]
