# Generated by Django 5.2.17 on 2026-09-13 20:08

import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('study', '0003_notes'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ReviewDay',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('local_date', models.DateField()),
                ('timezone', models.CharField(max_length=63)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('next_boundary_at', models.DateTimeField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='readerprofile',
            name='active_day',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='study.reviewday'),
        ),
        migrations.CreateModel(
            name='ReviewSchedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('interval_days', models.DecimalField(decimal_places=0, default=1, max_digits=100)),
                ('next_due_date', models.DateField(blank=True, null=True)),
                ('last_completed_at', models.DateTimeField()),
                ('generation', models.PositiveIntegerField(default=1)),
                ('suspended', models.BooleanField(default=False)),
                ('article', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='study.article')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ReviewSlot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ordinal', models.PositiveSmallIntegerField()),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('cancelled_at', models.DateTimeField(blank=True, null=True)),
                ('article', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='study.article')),
                ('day', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='slots', to='study.reviewday')),
                ('schedule', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='study.reviewschedule')),
            ],
            options={
                'ordering': ('ordinal',),
            },
        ),
        migrations.AddConstraint(
            model_name='reviewday',
            constraint=models.UniqueConstraint(fields=('user', 'local_date'), name='review_day_user_date_unique'),
        ),
        migrations.AddIndex(
            model_name='reviewschedule',
            index=models.Index(fields=['user', 'suspended', 'next_due_date'], name='review_user_suspended_due'),
        ),
        migrations.AddConstraint(
            model_name='reviewschedule',
            constraint=models.UniqueConstraint(fields=('user', 'article'), name='review_schedule_user_article_unique'),
        ),
        migrations.AddConstraint(
            model_name='reviewschedule',
            constraint=models.CheckConstraint(condition=models.Q(('generation__gte', 1)), name='review_generation_positive'),
        ),
        migrations.AddConstraint(
            model_name='reviewschedule',
            constraint=models.CheckConstraint(condition=models.Q(('interval_days__gte', 1), ('interval_days__lte', Decimal('9999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999'))), name='review_interval_bounds'),
        ),
        migrations.AddConstraint(
            model_name='reviewslot',
            constraint=models.UniqueConstraint(fields=('day', 'ordinal'), name='review_slot_day_ordinal_unique'),
        ),
        migrations.AddConstraint(
            model_name='reviewslot',
            constraint=models.UniqueConstraint(fields=('day', 'article'), name='review_slot_day_article_unique'),
        ),
        migrations.AddConstraint(
            model_name='reviewslot',
            constraint=models.CheckConstraint(condition=models.Q(('ordinal__gte', 0), ('ordinal__lte', 2)), name='review_slot_ordinal_bounds'),
        ),
    ]
