# Generated by Django 5.2.17 on 2026-09-13 21:07

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('study', '0004_reviews'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Digest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day', models.DateField()),
                ('payload', models.JSONField(default=dict)),
                ('idempotency_key', models.CharField(max_length=128, unique=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('sending', 'Sending'), ('sent', 'Sent'), ('skipped', 'Skipped'), ('failed', 'Failed'), ('unknown', 'Unknown')], default='pending', max_length=10)),
                ('first_attempt_at', models.DateTimeField(blank=True, null=True)),
                ('lease_until', models.DateTimeField(blank=True, null=True)),
                ('provider_id', models.CharField(blank=True, default='', max_length=200)),
                ('retry_until', models.DateTimeField(blank=True, null=True)),
                ('last_error', models.CharField(blank=True, default='', max_length=63)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'indexes': [models.Index(fields=['status', 'day'], name='digest_status_day')],
                'constraints': [models.UniqueConstraint(fields=('user', 'day'), name='digest_user_day_unique'), models.CheckConstraint(condition=models.Q(('status__in', ('pending', 'sending', 'sent', 'skipped', 'failed', 'unknown'))), name='digest_status_valid'), models.CheckConstraint(condition=models.Q(models.Q(('first_attempt_at__isnull', True), ('lease_until__isnull', True), ('retry_until__isnull', True)), models.Q(('first_attempt_at__isnull', False), ('lease_until__gt', models.F('first_attempt_at')), ('lease_until__isnull', False), ('retry_until__gt', models.F('first_attempt_at')), ('retry_until__isnull', False)), _connector='OR'), name='digest_attempt_window_valid'), models.CheckConstraint(condition=models.Q(models.Q(('status', 'sending'), _negated=True), ('first_attempt_at__isnull', False), _connector='OR'), name='digest_sending_has_attempt'), models.CheckConstraint(condition=models.Q(models.Q(('status', 'sent'), _negated=True), models.Q(models.Q(('provider_id', ''), _negated=True), ('first_attempt_at__isnull', False)), _connector='OR'), name='digest_sent_has_receipt')],
            },
        ),
    ]
